server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  session:
    redis:
      flush-mode: ON_SAVE
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
cloud:
  aws:
    s3:
      endpoint: ${AWS_S3_ENDPOINT}
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}
    credentials:
      secretKey: ${AWS_S3_SECRET_KEY}
      accessKey: ${AWS_S3_ACCESS_KEY}
    stack:
      auto: false
