spring:
  datasource:
    url: jdbc:mysql://localhost:3307/impostor
    username: root
    password:
  data:
    redis:
      host: 127.0.0.1
cloud:
  aws:
    s3:
      endpoint: http://localhost:4566
      bucket: local-bucket
      region: ap-northeast-2
    credentials:
      secretKey: secretKey
      accessKey: accessKey